src/TfsTimeline/ViewModels/BuildDefinitionViewModel.cs
namespace TfsTimeline.ViewModels
{
    public class BuildDefinitionViewModel
    {
        public string Link { get; set; }

        public string BuildName { get; set; }

        public bool Selected { get; set; }
    }
}

src/TfsTimeline/ViewModels/LinkListViewModel.cs
using System.Collections.Generic;

namespace Greenicicle.TfsTimeline.ViewModels
{
    public class LinkListViewModel
    {
        public string Title { get; set; }

        public IDictionary<string, string> Links { get; set; }
    }
}

src/TfsTimeline/Controllers/BuildsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using TfsTimeline.Models;
using TfsTimeline.ViewModels;

namespace TfsTimeline.Controllers
{
    public class BuildsController : Controller
    {
        private readonly IBuildService buildService;

        public BuildsController(IBuildService buildService)
        {
            this.buildService = buildService;
        }

        public ActionResult ProjectNamesView()
        {
            var projectNames = buildService.GetProjects();

            var viewModel = new LinkListViewModel
            {
                Title = "Projects on TFS",
                Links = projectNames.ToDictionary(
                    projectName => Url.Action("BuildNamesView", new { projectName }),
                    projectName => projectName)
            };

            return View("LinkListView", viewModel);
        }
        
        public ActionResult BuildNamesView(string projectName)
        {
            var buildNames = buildService.GetBuildDefinitions(projectName);

            var viewModel = new BuildDefinitionListViewModel
            {
                Title = string.Format("Builds for project {0}", projectName),
            };

            viewModel.BuildDefinitionList = new List<BuildDefinitionViewModel>();

            foreach (var buildName in buildNames)
            {
                viewModel.BuildDefinitionList.Add(new BuildDefinitionViewModel()
                    {
                        BuildName = buildName,
                        Link = Url.Action("BuildTimelineView", new { projectName, buildName })
                    });
            }

            return View("BuildDefinitionsView", viewModel);
        }

        public ActionResult BuildTimelineView(string projectName, string buildName)
        {
            return View(new LatestBuildsViewModel { ProjectName = projectName, BuildName = buildName });
        }

        [HttpPost]
        public ActionResult MonitorBuildsView(string projectName, string [] builds)
        {
            var selectedBuilds = builds.ToList().Where(x => x != "false").ToList();

            var buildMonioringViewModel = new BuildMonitoringViewModel
                {
                    BuildDefinitions = selectedBuilds,
                    BuildMonitoringUrl = this.Url.Action("LastBuildResults", "BuildsApi")
                };

            return View(buildMonioringViewModel);
        }
    }
}

src/TfsTimeline/Views/Shared/BuildDefinitionsView.cshtml
@model TfsTimeline.ViewModels.BuildDefinitionListViewModel


<!DOCTYPE html>

<html>
    <head>
        <title>@Model.Title</title>
    </head>
    <body>
        <h1>::: Build Monitor :::</h1>
        <h2>@Model.Title</h2>
        @using (Html.BeginForm("MonitorBuildsView", "Builds"))
        {
            <input type="submit" value="Monitor selected Builds" />
            foreach (var buildDefinition in Model.BuildDefinitionList)
            {
                <div>
                    @Html.CheckBox("builds", buildDefinition.Selected, new { value = buildDefinition.BuildName })
                    <a href="@buildDefinition.Link">@buildDefinition.BuildName</a>
                </div>
            }
        }
    </body>
</html>

src/TfsTimeline/Views/Shared/LinkListView.cshtml
@model TfsTimeline.ViewModels.LinkListViewModel


<!DOCTYPE html>

<html>
    <head>
        <title>@Model.Title</title>
    </head>
    <body>
        <h1>::: Build Monitor :::</h1>
        <h2>@Model.Title</h2>
        @foreach (var link in Model.Links)
        {
            <div>
                <a href="@link.Key">@link.Value</a>
            </div>
        }
    </body>
</html>

src/TfsTimeline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout.debug.js")" type="text/javascript"></script>
     <script src="@Url.Content("~/Scripts/tfs-timeline.common.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>